version: "3.8"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ~/data/doyun/maria:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    build:
      context: ./requirements/mariadb #도커 파일  위치
      dockerfile: Dockerfile #도커 파파일  이름
    networks:
      inception:
    env_file: .env

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ~/data/doyun/wordpress:/var/www/wordpress
    restart: always
    ports:
      - "9000:9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      inception:
    env_file: .env

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ~/data/doyun/wordpress:/var/www/wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      inception:
    env_file: .env

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/doyun/maria
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/doyun/wordpress

networks:
  inception:
    driver: bridge
